AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  FunctionArn:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool

  ResourceServer:
    Type: Custom::CognitoResourceServer
    Properties:
      ServiceToken: !Ref FunctionArn
      UserPoolId: !Ref UserPool
      Identifier: example-user-pool-client
      Name: example-user-pool-client
      Scopes:
      - ScopeName: scope-name
        ScopeDescription: scope-description
